### ISSUE TITLE
changes for REM broke bots

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#14]
Somewhere between 4d28f65346de821c4c2a11ddfb778471b64f2fcc and the latest work, the bots broke. The telegram bot (running the app directly, as otherwise it's not logged, will raise a separate issue) reports:
```
App is polling Telegram API
Received flood report request
Error getting card: Error getting card: null{"statusCode":401,"body":{"status":401,"message":"No authorization token was found","code":"credentials_required","name":"UnauthorizedError"},"headers":{"content-type":"application/json; charset=utf-8","content-length":"116","connection":"close","date":"Fri, 13 Jan 2017 22:00:26 GMT","access-control-allow-origin":"*","access-control-expose-headers":"Link","etag":"W/\"74-OSQeIKTABoFDPuRFUQxJyg\"","x-amzn-remapped-connection":"keep-alive","x-amzn-remapped-content-length":"116","x-amzn-remapped-date":"Fri, 13 Jan 2017 22:00:26 GMT","x-amzn-remapped-server":"nginx/1.10.1","x-amzn-requestid":"b0c4c759-d9db-11e6-93ec-e14214c1d52c","x-powered-by":"Express","x-response-time":"1.217ms","x-cache":"Error from cloudfront","via":"1.1 293b8f3272c0685f690ebc81ed0b2d34.cloudfront.net (CloudFront)","x-amz-cf-id":"ihA-pOIZAxwe6HPgnPTsghp5fELQE_yd_h1q2Cpg64O-TOh3ge6y_Q=="},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"data.petabencana.id","port":443,"hostname":"data.petabencana.id","hash":null,"search":null,"query":null,"pathname":"/cards","path":"/cards","href":"https://data.petabencana.id/cards"},"method":"POST","headers":{"x-api-key":"our-API-key","Content-Type":"application/json","accept":"application/json","content-length":61}}}
```

The twitter bot isn't logging an error in the log file but it's missing the final reply saying (EN): "Hi! Thanks for your report. I've put it on the map..." 

Maybe you've got a syntax error / something applied too widely in routing that's causing the auth to be applied to other routes?

**Comment by matthewberryman** [comment]
@mgvarley There's a jwtcheck that's been in /cards for a while, just not used because you've only recently implemented a proper jwtcheck rather than just leaving it with some values defined in config. I can remove for now. If you want to implement in future @talltom you'd need to change the code across a number of repositories that call it.

**Comment by matthewberryman** [comment]
This would also affect qlue as well, as there's a jwtcheck on /feeds too

**Comment by matthewberryman** [comment]
Ok I checked and those paths are protected by API key, so I can just kill the call jwtcheck there. I will work on that now @talltom and @mgvarley

**Comment by mgvarley** [comment]
Hi all, I just swapped out one type of recommended auth0 jwt check logic for another, not sure why this suddenly locked down these other routes. Auth0 are rolling out changes at the moment and it's a bit of a mess. In the longer term we should have a common authentication strategy for everything but at the moment this is not possible so we need jwtcheck for client side auth (rem) and api gw auth for everything else. Note that the api gw auth we have at the moment can be circumvented by hitting the beanstalk apps directly as these are public. @talltom we can have a quick chat on this next week if you like.

Also now that my current phase of work is up I will be coming off of Gitter and won't be watching the repos but if you need my help feel free to email me.


Thanks

Mark




Sent with Unibox

**Comment by matthewberryman** [comment]
The other auth method would have to be implemented in cognicity-reports-* code. @talltom I had a chat with @mgvarley about above issues on whatsapp. I have that plus a few other things on my post launch to-do list that I will put up on urbanriskmap-meta on Monday arvo my time. @mgvarley thanks for all your help.
