### ISSUE TITLE
file extension support

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#24]
At the moment we have hard coded the file extension to be jpg (which will cover photos, but not images from other sources)
https://github.com/urbanriskmap/cognicity-server/blob/chennai/src/api/routes/cards/index.js#L157
We should derive extension from content-type.

**Comment by matthewberryman** [comment]
pngs still work however (see test at https://dev.riskmap.in/map/chennai/17 ) as https://github.com/urbanriskmap/image-lambda libraries are looking at file magic metadata not extension

**Comment by abrahamq** [comment]
browsers also do this. I'll fix early next week probably? Writing thesis proposal now.

**Comment by tomasholderness** [comment]
@abrahamq check with @ojha-url think there is a client side restriction on this (possibly due to image preview handling in cards)

**Comment by tomasholderness** [comment]
@abrahamq, checked with @ojha-url and you should be able to set this to be any valid image format. Previous stuff on client side limitations got fixed.

**Comment by tomasholderness** [comment]
Fixed in fbb71c02eeb2250cf05d2339d4a1ece5d7799d5f
