### ISSUE TITLE
support non-base64-encoded Auth0 secrets

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#3]
From email:
In the past, the client secret associated with each client was base64-encoded. In order to enable dynamic client registration, compliant with the OpenIDConnect specification, we need to make a change to store client secrets without base64 encoding.

To make this transition easier for our customers, all existing client secrets will remain base64-encoded. Client Secrets for new clients created after the change will not be base64 encoded. All existing clients will continue to work as-is. If you change a secret (via Dashboard or API) that is currently encoded, after this change, it will stay encoded.

We are also introducing a new endpoint (POST/api/v2/clients/{id}/rotate-secret) to allow customers to rotate their client secret. When calling this endpoint, Auth0 will generate a new, non base64 encoded, secret for the client, even if the secret was previously encoded. You should not use the /rotate-secret endpoint if you need to keep the client secret encoded; you may provide your own secret via Dashboard or API if you need to change the secret and still keep it encoded.

**Comment by tomasholderness** [comment]
Think this got left open from initial development.
Our client secret is manually base64-encoded here: https://github.com/urbanriskmap/cognicity-server/blob/master/src/lib/util.js#L20
