### ISSUE TITLE
Migrate authentication to use new Auth0 API flow

### ISSUE THREAD

**Issue by mgvarley** [urbanriskmap/cognicity-server#4]
Auth0 are in the process of rolling out support for API authentication which has a lot of advantages for more fine grained control and mixed use cases such as trusted clients (e.g. our lambda reporting collector functions) and single page applications such as the REM both calling the same API.  At the time of writing this is only available in the US region and is being rolled out to other regions: https://auth0.com/docs/api-auth

**Comment by tomasholderness** [comment]
Closing this as not priority.
