### ISSUE TITLE
Should we check-in package-lock.json as recommended by NPM

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#44]
https://docs.npmjs.com/files/package-lock.json
**discuss...**

**Comment by matthewberryman** [comment]
If we want compatibility with ElasticBeanstalk we need to use npm-shrinkwrap.json (effectively the same for now, see https://stackoverflow.com/questions/44258235/what-is-the-difference-between-npm-shrinkwrap-json-and-package-lock-json for more details)

**Comment by tomasholderness** [comment]
Thanks @Matthew, I would propose the following then:
1) staying on npm <5 until https://github.com/npm/npm/issues/17146 is fixed
2) adding package-lock.json to gitignore 
3) generating npm-shrinkwrap.json with each release by doing `npm shrinkwrap`

Let me know if you and @abrahamq both agree!

**Comment by matthewberryman** [comment]
1. We should stay on the same node and npm major version as ElasticBeanstalk until that changes - your local environment should match our dev and prod environments as closely as possible, and I recommend use of [nvm](https://github.com/creationix/nvm) to maintain different versions of node as required.
2 & 3 - agreed.

**Comment by matthewberryman** [comment]
See http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs for versions (currently node v6.10.0, npm v3.9.5)

**Comment by tomasholderness** [comment]
Update:-
- node and npm versions are now specified in the "engines" tag of package.json
- npm-shrinkwrap.json is now in the dev branch
- instructions for building and updating shrinkwrap added to readme
- Jenkins build node version changed to install specific npm version (npm@3.10.10)
- Travis build node version changed to install specific npm version (npm@3.10.10)

Note that AWS EB uses NPM@3.10.10 not NPM@3.9.5 as specified in [docs](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs)

@matthewberryman do you want to leave this open as a reminder to change the node build environment in Jenkins when we push to master?

**Comment by matthewberryman** [comment]
AWS EB now supports node v8 / npm v5 so we should move to using package-lock.json. Can I leave it to MIT team to update code & docs, and I will update jenkins and EB (after you have tested locally first and confirmed)?

**Comment by tomasholderness** [comment]
OK thanks @matthewberryman - tracking the update of Node here: https://github.com/urbanriskmap/cognicity-server/issues/50
