### ISSUE TITLE
Are we happy that dev and prod share the same AWS S3 bucket?

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#47]
- @matthewberryman what are your thoughts?

**Comment by tomasholderness** [comment]
- note that unit tests use separate "testing-petabencana-image-uploads"
- there is also, an old "testimageuploadpetabencana" @abrahamq do we need this?

**Comment by matthewberryman** [comment]
Probably not, 
1. From the perspective of card ID collision (how are these generated?)
2. From the perspective of keeping dev test/demo images separate.

Will update the AWS infrastructure here.

**Comment by matthewberryman** [comment]
AWS infrastructure (incl. tweaked recognition code) set up, will configure use of it once we are sorted with database issue to fix image_url issue as per https://github.com/urbanriskmap/cognicity-server/issues/48#issuecomment-312526417

**Comment by tomasholderness** [comment]
Great. Thanks. Separate buckets sound optimal.

Unique codes generated using [shortid library](https://www.npmjs.com/package/shortid). Chance of collision small, but better to be robust.

@matthewberryman, @abrahamq also confirmed we can delete the "testimageuploadpetabencana" bucket.
