### ISSUE TITLE
JSdocs in the dev branch? 

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-server#49]
I don't think that we should have compiled jsdocs in the repo. Looks like the jsdoc/ folder was added in 4da67946

This clutters the repo with an almost complete copy of the code and it's something you can just generate on your local machine/ on jenkins if we decide we want to host the jsdocs later? 

Thoughts?

**Comment by tomasholderness** [comment]
Yes, perhaps we should put these somewhere? If we don't have them and only build them locally, we won't use them.

**Comment by tomasholderness** [comment]
So I moved the docs to gh-pages branch (see https://urbanriskmap.github.io/cognicity-server/jsdoc/) - this is a really crappy flow though, as now can't merge new changes into this branch to perform code updates.

- we should probably have a deployment step that builds and pushes to hosting somewhere? I.e. an S3 bucket.

What are your thoughts?

**Comment by abrahamq** [comment]
Every time we build dev on jenkins we also push docs to a s3 bucket? That sounds pretty cheap and effective?

**Comment by matthewberryman** [comment]
Agreed- sounds good. Can drop cloudfront in front of s3 too.
Also, I’m thinking we could probably replace Jenkins with Travis? I have been using that for s3 ( see https://github.com/acrossthecloud/acrossthecloud.net/ ) and serverless ( see https://github.com/matthewberryman/midsomerplots/ ) on my own / company’s projects, and note they support Elastic Beanstalk as well. Thoughts?

Sent from my iPhone

On 25 Aug 2017, at 19:18, Abe <notifications@github.com<mailto:notifications@github.com>> wrote:


Every time we build dev on jenkins we also push docs to a s3 bucket? That sounds pretty cheap and effective?

**Comment by tomasholderness** [comment]
Sounds great. I think docs.petabencana.id is great for the API and is very readable for downstream consumers so should stay as is, where shall we put these cognicity server (internal) code docs?

@matthewberryman - strongly in favor of moving to Travis; were you thinking of hosting our own solution or using existing service? Note that now that we're deploying across 3 instances (Indonesia, India, US) for every push to master we potentially trigger multiple builds of multiple components (E.g. server, web, cards) so their solution would probably reduce load on our systems (i.e. against self hosted server) and they're free for open source projects.  We just need a backup plan for deployments in case they go down.

**Comment by tomasholderness** [comment]
@ojha-url is building ESDocs for client apps (maps, cards etc.) should put these in the same bucket / different folder.

**Comment by tomasholderness** [comment]
@abrahamq JSDocs moved out of the master branch with [v3.0.2 release](https://github.com/urbanriskmap/cognicity-server/releases/tag/V3.0.2) - perhaps you and @corymj could setup a build script in Travis to deploy these to an S3 bucket?

**Comment by tomasholderness** [comment]
@abrahamq @corymj - any update on this?

**Comment by abrahamq** [comment]
Hey, sorry for falling behind on this. It is now done and there's a pull request for the branch jsdocsToS3. You can view the up to date docs here: http://dev-cognicity-server-docs.s3-website-us-east-1.amazonaws.com/test_testDB%250AA%2520module%2520to%2520test%2520the%2520db%2520utility%2520modulemodule_.html

Didn't set up hostname/cloudfront. What are thoughts for hostnames? maybe docs-internal.petabencana.id ?

**Comment by tomasholderness** [comment]
Closing this as issue resolved for this repo. Need discussion of cross-repo internal documentation web service.
