### ISSUE TITLE
Upgrade to node v8 / npm v5

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#50]

**Comment by tomasholderness** [comment]
@matthewberryman do you know what version of NPM EB uses? Still listed as 3.9.5 https://aws.amazon.com/releasenotes/9182044408953348

**Comment by matthewberryman** [comment]
That's the default for the default version of node.js, if you select 8.1.4 as the node version it uses npm 5.0.3 per http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.nodejs (and I verified it's 5.0.3 on an EB EC2 instance I have on another project already running on node v8.1.4).

**Comment by tomasholderness** [comment]
Great thanks. Will start testing with these versions.

**Comment by tomasholderness** [comment]
Barp :/

@matthewberryman when attempting to update node settings in EB

```sh
NodeVersion: Invalid option value: '8.1.4' (Namespace: 'aws:elasticbeanstalk:container:nodejs', OptionName: 'NodeVersion'): Value is not one of the allowed values: [4.6.1, 4.8.0, 5.12.0, 6.9.1, 6.10.0, 7.6.0] 
```

**Comment by matthewberryman** [comment]
I’ll get onto this once I get back home (nearly there). Possibly the AMI is out of date?

Sent from my iPhone

On 26 Aug 2017, at 06:35, Tomas Holderness <notifications@github.com<mailto:notifications@github.com>> wrote:


Barp :/

@matthewberryman<https://github.com/matthewberryman> when attempting to update node settings in EB

NodeVersion: Invalid option value: '8.1.4' (Namespace: 'aws:elasticbeanstalk:container:nodejs', OptionName: 'NodeVersion'): Value is not one of the allowed values: [4.6.1, 4.8.0, 5.12.0, 6.9.1, 6.10.0, 7.6.0]

**Comment by tomasholderness** [comment]
Ok thanks. Please try this on dev only as we need to discuss https://github.com/urbanriskmap/cognicity-schema/issues/28 so don't make any further deployments of DEV server code to PROD at this time. 👍

**Comment by matthewberryman** [comment]
'twas as I thought—the AMI used was getting old. Upgraded that and then put 8.1.4 on dev EB. Leaving this ticket open until you've tested.

**Comment by matthewberryman** [comment]
(prod AMI also updated to pick up security patches and in preparation but left the node/npm versions alone for now)

**Comment by tomasholderness** [comment]
Node version was updated in package.json with [v3.0.2](https://github.com/urbanriskmap/cognicity-server/releases/tag/V3.0.2)
@matthewberryman - if you're happy one of us can update EB prod environment?

**Comment by matthewberryman** [comment]
Updated to node v8.4.0 across the board.
