### ISSUE TITLE
Update patch handler validation

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/cognicity-server#51]
https://github.com/urbanriskmap/cognicity-server/blob/3b4967078d808f129bf1c372bb5503c681b66434/src/api/routes/cards/index.js#L234

Update Joi string length check to receive full url strings from client, eg. https://images-dev.petabencana.id/[card_id].jpg

**Comment by ojha-url** [comment]
Or append url in server itself, using deployment specific config params

**Comment by tomasholderness** [comment]
Agreed with @ojha-url - appending on server. Fixed in 1ab597e3f835626290417b985bb952d290d0f747
