### ISSUE TITLE
shortid issues

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#53]
There are a few issues with shortid:
1. On MSF-REACH, we had a report of URLs breaking in twitter if they had a '-' on the end. I couldn't reproduce this in Twitter desktop in Chrome on Mac (same setup as person who reported it); that said I have noticed the Twitter mobile client sometimes breaks on rfc3986-compliant URLs before, particularly with non-alphanumeric characters. Issue usergroupcoop/msf-reach#93 and fix usergroupcoop/msf-reach@41bc78f (plus some database fixes for existing shortids).
2. https://www.npmjs.com/package/shortid "If you are running multiple server processes then you should make sure every one has a unique worker id. Should be an integer between 0 and 16." We have multiple ec2 instances each running a copy of the cognicity-server/msf-reach code. So we should implement this. The default is to pick this up from an environment variable, however EB sets up the environment variables the same across both instances. As a hack, we could get the instance id from http://169.254.169.254/latest/meta-data/instance-id (an internal link on each instance) and then convert that an integer between 0 and 16.
3. We should possibly also look at seeding it too via https://www.npmjs.com/package/shortid#shortidseedinteger
(and if you want to seed using satellite data, check out https://github.com/matthewberryman/astroseed ;)
4. @talltom [says](https://github.com/urbanriskmap/cognicity-schema/issues/28) 'OTLs good up to "millions" what ever that means'—it means eventually the sequence (basically from a prng) will repeat. Need to explore what prng shortid uses and there are some known to have very long sequences that we could possibly replace it with.

@talltom suggested: 'Re. Short id; a more robust alternative would be postgres uuid. Single point of origin (no duplicate servers) and much "more unique"'
My 2c: that's possibly less work than at least 2 & 4 (I would say 3 is optional, and 1 is already solved) ?

**Comment by tomasholderness** [comment]
@matthewberryman, so there are two issues? Want to make sure I've got the gist.

1) URL "validity" of tokens generated using shortid (e.g. with "-" etc.)
2) The potential for duplicates given parallel nature of our deployment

**Comment by matthewberryman** [comment]
@talltom That's pretty much it. 3 and 4 are more general cases where you get duplicates irrespective of parallel deployment.

**Comment by tomasholderness** [comment]
@matthewberryman; UUIDs contain "-", for example

```json
"cardId": "717c6379-773b-410b-972c-54911cacd89f"
```

would that work as URL? 

e.g. http://localhost:8001/cards/717c6379-773b-410b-972c-54911cacd89f

**Comment by matthewberryman** [comment]
I'm pretty sure the issue was related to having a "-" on the end, which is guaranteed not to be the case for UUIDs. I will do some testing later tonight my time regarding twitter and facebook and telegram.

**Comment by tomasholderness** [comment]
Dev server changed to work with UUIDs generated by schema.

server: 013d71f60cf0524169ba6e321571fcebeeb8303f
schema: https://github.com/urbanriskmap/cognicity-schema/commit/6ba38b99077d6853a088af99da00be985328e453
