### ISSUE TITLE
Baked in paths in swagger-api.json

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-server#65]
"petabencana.id" is baked into the swagger-api.json file. How is this currently working for multi region deployments?

**Comment by tomasholderness** [comment]
This is a function of downloading the swagger spec from API gateway. Not sure how we'd create a generic solution, without starting with the swagger file and having a deployment variable (e.g. in Travis?).

**Comment by matthewberryman** [comment]
You'd have to use cloudformation (and cloudformation variables) to achieve it; it's not something that I think you could do with serverless alone and in particular we have bits and pieces of the API across a few different places (e.g. cognicity-server but the stats API is deployed separately via serverless). Also, just noting that the swagger in the repo is not necessarily up to date, I will update it soon. I have been downloading the swagger, doing search and replace on domain name, and then uploading, and then deploying the services (via jenkins etc.) and then doing any fine tuning required (e.g. to link to stats APIs requires setting permissions via AWS CLI commands that come from API GW suggestions as you link them).

**Comment by matthewberryman** [comment]
updated in c56214589be4d1fe6727ae187370f26d108cc7fc
