### ISSUE TITLE
Is there a Qlue feed for Semarang?

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#69]
- if so Tom needs to update src/config.js `  API_FEEDS_QLUE_CITIES: (process.env.API_FEEDS_QLUE_CITIES || 'jabodetabek,bandung,surabaya').split(',')`

ping @prittandrani @emirhartato

**Comment by prittandrani** [comment]
hi @talltom ! We have not talked to Qlue yet about this until now, but seems they have another apps deployed in Semarang. We met several government officials briefly (including BPBD) but they did not mention Qlue, instead they have their own local applications from city government.
We are planning to have a meeting with Semarang government together with PDC & HOT in a few weeks, so we will get back to you after that if that is sounds okay for you?

cc @fadmastuti @fadmastuti

**Comment by tomasholderness** [comment]
Hi @prittandrani. Great, if there is a Qlue feed we can add it in the new year. Thanks.
