### ISSUE TITLE
/floods + REM endpoints

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#7]
Previously /floods was public and returning a list of floods, which should be public. Now it's been changed so it requires authentication. We need to clear up the intent of this API route - is it for returning the (read only) public view and do we want to have a separate end point for REM changes (see https://github.com/urbanriskmap/cognicity-server-v3/blob/master/src/api/routes/floods/index.js#L54 ), or do we want to have a combined endpoint, in which case we probably only want to protect POST but not GET.

**Comment by tomasholderness** [comment]
- [GET] public
- [PUT] private/Auth0.
I have discussed this with @mgvarley, but REM is still in development.

**Comment by tomasholderness** [comment]
This is fixed in prod and floods are available.
