### ISSUE TITLE
tidy up unused API GW methods

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-server#73]
For /reports/{id} only [GET](https://github.com/urbanriskmap/cognicity-server/blob/6ede5fc72b44f849be09f979f7f9b2af873da9fb/src/api/routes/reports/index.js#L61) and [PATCH](https://github.com/urbanriskmap/cognicity-server/blob/6ede5fc72b44f849be09f979f7f9b2af873da9fb/src/api/routes/reports/index.js#L81) and OPTIONS (for CORS pre-flight) used, but any method is [defined in API GW](https://github.com/urbanriskmap/cognicity-server/blob/dev/apigw/pb/swagger.json#L1827) as acceptable.

@talltom I will test out the changes for this on dev, can you please have a look through and see if there are any other resources we can tighten up in the API as you go through documenting the API.

**Comment by matthewberryman** [comment]
@talltom @abrahamq I have tested using both postman and on https://dev.petabencana.id/map/jakarta/4225 and all seems good with respect to GET, PATCH and OPTIONS.

**Comment by tomasholderness** [comment]
`/infrastructure/{type}` should also just be GET.

**Comment by matthewberryman** [comment]
Ok, let me know when you're finished reviewing @talltom and I will make further changes as necessary then.

**Comment by tomasholderness** [comment]
Yes, there's also ANY set on `/floods/id` and `/cards/id` which I will look into.

**Comment by tomasholderness** [comment]
`/floods/id`
requires only:
- PUT
- DELETE

**Comment by tomasholderness** [comment]
`/cards/id`
requires:
- GET
- PUT

Also note #74 in progress.

**Comment by tomasholderness** [comment]
@matthewberryman - above comments cover it. Once you've pulled down updated Swagger file(s) I'll probably do another point release for PROD as looking at [CHANGELOG](https://github.com/urbanriskmap/cognicity-server/blob/dev/CHANGELOG.md) for v3.0.5 there's a few new things.

**Comment by matthewberryman** [comment]
@talltom 
1. /infrastructure/{type} also is listed as ANY but looks like you're only using GET. Anything else planned?
2. Ditto /floodgauges/{id}
3. /cards/{cardId} also requires a HEAD method according to the code https://github.com/urbanriskmap/cognicity-server/blob/9f23771ae3c7c675003f56cbcb0f4ba15e209869/src/api/routes/cards/index.js#L74 - is this something you use in riskmap/testing ? Let me know either way, and if not then remove the unused server code.

**Comment by matthewberryman** [comment]
Update:
* Tightened up (and tested) reports a bit further with https://github.com/urbanriskmap/cognicity-server/commit/f1c2d4c5acf2acc18d3592243ee26799f04a1cad
* I made a similar change to remove greediness in path matching for /floods in https://github.com/urbanriskmap/cognicity-server/commit/fc3bf3104aba2d60c05ffd8b61e53701aa5c25f2 along with a change of name convention (not required functionally but wanted to match cognicity-server code) although that had a bug I fixed as part of
* https://github.com/urbanriskmap/cognicity-server/commit/24dc4f86a38da42955f8f88166678492b4669236 to tighten up floods as [mentioned](https://github.com/urbanriskmap/cognicity-server/issues/73#issuecomment-356693217) - I also went back to cognicity-server and riskmap-rem source to see what the query parameters and headers are (and if they're required or optional) and I think I have set this correctly; I will test on rem-dev UI now and if any issues will fix and report back here.

To-do:
* I will open a private repo for postman and would like to work on that before further work on this issue.

**Comment by matthewberryman** [comment]
Ok adding a required and validated query string parameter to API GW means it's actually duplicated before it's passed on to the server (logs from EB server below, see that there are two copies of username which of course breaks our checks)—I checked and as expected not due to the greedy change, it may be due to the use of HTTP proxying although even that is weird. We're checking anyway in cognicity-server so it doesn't hurt to leave these off of API GW.

info: ::ffff:127.0.0.1 - - [11/Jan/2018:00:47:36 +0000] "PUT /floods/509?username=my_username&username=my_username HTTP/1.1" 400 169 "https://rem-dev.petabencana.id/map" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.71 Safari/537.36"

d7b0a96 fixes this issue, and have tested PUT and DELETE requests for /floods/{localAreaId} through rem-dev and all good now.
