### ISSUE TITLE
Optional query param 'agency' for sensors

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/cognicity-server#90]
Need to add a `?agency=usgs` query param for GET @ sensors.riskmap.us?
https://urbanriskmap.github.io/cognicity-api-docs/#get-all-sensors

This would help in reducing processing time in the following processes:
* add sensors lambda (USGS)
* upload stations lambda (SFWMD)
* add sensor data lambda (USGS)
* add station data lambda (SFWMD)
* each client side GET call to filter mapbox layers

Refer these:
https://github.com/urbanriskmap/riskmap-ng/issues/21
https://github.com/urbanriskmap/cognicity-sensors-etl-us/issues/3

**Comment by tomasholderness** [comment]
Fixed over in the sensors repo: https://github.com/urbanriskmap/cognicity-sensors/commit/04ba50e16c50c39e6b43519679b2ed5f3d3bfc7f
