### ISSUE TITLE
infrastructure/sites returns null when used with ?city param

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/cognicity-server#96]
Is it because of [this](https://github.com/urbanriskmap/cognicity-schema/commit/754d56366a154d193a2b9908fd84615d8ad37448) pending deployment?

**Comment by tomasholderness** [comment]
Its because there is no `instance_region` tag set in the sites data: https://github.com/urbanriskmap/cognicity-schema/blob/dev/data/us/infrastructure/sites.sql

**Comment by tomasholderness** [comment]
For example, compare to the basins data where the tags are set: https://github.com/urbanriskmap/cognicity-schema/blob/dev/data/us/infrastructure/basins.sql

**Comment by talltom** [comment]
https://github.com/urbanriskmap/cognicity-schema/issues/54

**Comment by tomasholderness** [comment]
Fixed over in schema.
